#!/usr/bin/env pwsh
# =============================================================================
#  UserDashboard.ps1
#  Version v31
#  Single Pode app that replaces Glance: serves the dashboard AND handles
#  per-user toggles, with identity from Cloudflare Access (JWT verify).
#
#  CONFIG IS READ FROM ENVIRONMENT VARIABLES, set in Portainer:
#  your stack > Environment variables (the box below the YAML editor).
#  $env: values are process-level, so they're visible inside Pode's route
#  runspaces. The two CF_ vars are REQUIRED; if either is missing the app
#  prints a loud CONFIG ERROR and exits (so a misconfig is obvious, not silent).
#
#    CF_TEAM_DOMAIN   REQUIRED. e.g. https://nogoodreason.cloudflareaccess.com (no trailing slash)
#    CF_ACCESS_AUD    REQUIRED. Application Audience (AUD) tag for the gunit Access app
#    DASH_STATE_DIR   optional. container path where prefs are mounted (default /userprefs)
#    DASH_PORT        optional. listen port (default 8080)
#    DASH_DEVMODE     optional. "true" to bypass auth for local testing (NEVER in prod)
#    DASH_DEVEMAIL    optional. identity used when DASH_DEVMODE is true
#
#  The toggle JSON files are the ONLY contract with the media pipeline:
#  the pipeline reads <DASH_STATE_DIR>/<email>.json and acts on it.
# =============================================================================

Import-Module Pode

# Version stamp — bump on every change so stale images are obvious in `docker logs`.
# v18: /covers route now reads <cfgDir>/lists/covers (was <cfgDir>/covers) to
#      match where link-md writes book-list cover images. Fixes cover 404s.
# v19: dashboard links can carry an optional Sub (lighter second line, rendered
#      as <span class="custom-link-sub">). "Lists of Books" button gets a
#      subtitle. Added /favicon.ico route (serves <cfgDir>/favicon.ico if
#      present; absent -> route not registered, harmless 404).
# v20: Get-SubListHtml wraps each book's post-title content (cover + h5 + body)
#      in <div class="book-flow"> so the cover float is contained and the
#      author/description wrap to the cover's right then reflow below it. Title
#      (h4) stays outside the wrapper, full width at the top.
# v21: book layout reworked — cover + h5 rows now sit in a flex .book-head (h5
#      group vertically centred against the cover), and the description follows
#      below the head so it always starts under the cover at full width. Renderer
#      splits each book into .book-head (cover + .book-meta of h5s) then body.
# v22: first body paragraph tagged class="lead" (restores the prominent blue
#      intro the old `h5 + p` selector used to give). Coverless books get
#      class="nocover" on .book-flow so the template indents their body to rail 2.
# v23: if a book's body opens with a markdown blockquote (> …), it's left as a
#      <blockquote> pull-quote and NOT promoted to a lead <p> — lets a list use
#      "> The Booker judges said…" as an attributed opener. (Template adds sticky
#      h1 + distinct h1/h2/h3 styles + pull-quote blockquote styling.)
# v24: "Browse the library" link gets a Sub subtitle "Pick for Kindle here".
# v25: section headings (<h2>/<h3>) that appear AFTER a book in a list are now
#      pulled out of the book's .book-flow wrapper and emitted as top-level
#      siblings — fixes position:sticky on a mid-list h2 (it was sticking to the
#      small wrapper instead of the page, so it appeared not to stick).
# v26: book numbers are now AUTO-GENERATED by a CSS counter — markdown no longer
#      carries "NNN."; the renderer strips any manual number and injects an empty
#      .booknum hook. ([resetnum] markers are stripped for now; mid-list reset is
#      a future per-section-wrapper job.)
# v27: each book's h4 + flow is now wrapped in <div class="book"> so the sticky
#      book-title is bounded to its own book — a finished (possibly two-line)
#      title is pushed out by the next book instead of leaving a ghost row.
# v28: removed the trailing space after the empty .booknum span — the span is a
#      fixed-width inline-block spanning rail-1→rail-2, so the space pushed the
#      title ~4px past rail 2 (visibly misaligned on coverless books). Title now
#      sits flush at rail 2 with the body.
# v29: REVERTED the v27 .book wrapper. Bounding h4 to a per-book div meant short
#      books gave the title no scroll range to pin over. h4 + .book-flow are now
#      direct children of .booklist-page again, so h4 sticks continuously and the
#      next book's h4 evicts it (same sticky top). Ghosting now handled in CSS
#      (template v76: opaque bg + seam box-shadow on h4).
# v30: RE-RESTORED the .book wrapper. v29's premise was wrong: same-`top` sticky
#      siblings don't evict each other, they overlap, so a one-line h4 painting
#      over a two-line one left the old title's 2nd line showing below the new
#      title. The wrapper bounds each h4 to its book so it rides up and clears.
#      The original short-book pinning fear is moot now the template's JS slot-
#      tracker (v77) drives the h4 offset from the live section-bar height.
$script:DashVersion = 'UserDashboard v31'

Start-PodeServer {

    "==== $script:DashVersion starting ====" | Out-Default

    # --- config accessor: reads $env: (set via Portainer's Environment
    #     variables box). $env: is process-level so it's visible inside Pode's
    #     route runspaces. Set CF_TEAM_DOMAIN and CF_ACCESS_AUD in Portainer.
    function Get-Cfg([string]$name, [string]$default = '') {
        $v = [Environment]::GetEnvironmentVariable($name)
        if ([string]::IsNullOrWhiteSpace($v)) { return $default }
        return $v
    }

    # --- FAIL LOUD on missing required config, but print WHY before exiting so
    #     the logs aren't empty. (A bare crash restart-loops with no message.)
    $missing = @()
    if ([string]::IsNullOrWhiteSpace((Get-Cfg 'CF_TEAM_DOMAIN'))) { $missing += 'CF_TEAM_DOMAIN' }
    if ([string]::IsNullOrWhiteSpace((Get-Cfg 'CF_ACCESS_AUD')))  { $missing += 'CF_ACCESS_AUD' }
    if ($missing.Count -gt 0) {
        "*** CONFIG ERROR ***" | Out-Default
        "Missing required environment variable(s): $($missing -join ', ')" | Out-Default
        "Set them in Portainer > your stack > Environment variables, then redeploy." | Out-Default
        "*** Exiting. ***" | Out-Default
        throw "Missing required config: $($missing -join ', ')"
    }

    $port = [int](Get-Cfg 'DASH_PORT' '8080')
    Add-PodeEndpoint -Address 0.0.0.0 -Port $port -Protocol Http

    # Log errors and requests to the terminal so `docker logs` shows failures.
    New-PodeLoggingMethod -Terminal | Enable-PodeErrorLogging
    New-PodeLoggingMethod -Terminal | Enable-PodeRequestLogging

    # Local config dir (fast disk on otis, NOT the slow NAS). Holds the
    # editable files: template.html, instructions.md, users.json.
    $cfgDir = Get-Cfg 'DASH_CONFIG_DIR' '/config'
    Set-PodeState -Name 'CfgDir' -Value $cfgDir | Out-Null

    # Toggle DEFINITIONS stay in the script: they are logic (they map to keys
    # the storage + pipeline understand), not free-text content. Add one here
    # to add a setting; that does need a rebuild, unlike the editable content.
    $script:ToggleDefs = @(
        @{ Key = 'kindleSync'; Label = 'add books I download to Kindle sync list automatically'; Default = $false }
        # calibreBusy: a "don't interrupt me" switch for when Rob is using the
        # Calibre desktop GUI. While ON, the import watcher/sweep DEFER instead of
        # killing the GUI to free the library lock. Stored as an EXPIRY TIMESTAMP
        # (epoch seconds) so it AUTO-CLEARS after 2h even if left on. Restricted to
        # Rob's account (only he uses the desktop GUI; others use calibre-web which
        # never holds the lock). 'Expiry = 7200' seconds = 2 hours.
        @{ Key = 'calibreBusy'; Label = "I'm using Calibre desktop now — pause auto-import for 2h (don't interrupt)"; Default = $false; Users = @('shops@rob.me.uk'); Expiry = 7200 }
        # @{ Key = 'notifyEmail'; Label = 'Email me when a download finishes'; Default = $false }
    )
    Set-PodeState -Name 'ToggleDefs' -Value $script:ToggleDefs | Out-Null

    # Dashboard LINKS stay in the script (they change rarely; keeping them in
    # code means they're version-controlled and can't go missing). Edit here +
    # rebuild to change them. (Greetings + instructions are editable files.)
    # An optional Sub = '...' renders a lighter second line inside the button.
    $script:DashLinks = @(
        @{ Title = 'Browse the library'; Sub = 'Pick for Kindle here'; Url = 'https://books.rob.me.uk/discover/stored'; External = $true }
        @{ Title = 'Request a book from the server'; Url = 'https://request-books.rob.me.uk';         External = $true }
        @{ Title = 'Lists of Books'; Sub = 'Prizes, recommendations, summer reads etc'; Url = '/lists';      External = $false }
        @{ Title = 'How to use all this';                                Url = '/how-to-use'; External = $false }
    )
    Set-PodeState -Name 'DashLinks' -Value $script:DashLinks | Out-Null

    # Top nav bar items. Internal routes (/lists, /how-to-use) keep the nav bar
    # because they're same-origin pages served by this app. External links
    # (Browse, Request) are same-tab handoffs to the Cloudflare-Access apps —
    # they CAN'T be framed (X-Frame-Options/CSP + Access login), so we navigate
    # away rather than cage them. Edit text/URLs here + rebuild.
    #   External = $true  -> full URL, leaves the dashboard
    #   External = $false -> internal route path on this app
    $script:NavItems = @(
        @{ Title = '<svg viewBox="0 0 24 24" width="18" height="18" fill="currentColor" aria-label="Home" style="vertical-align:-3px"><path d="M12 3 2 12h3v8h6v-5h2v5h6v-8h3z"/></svg>'; Href = '/'; External = $false }
        @{ Title = 'Library';        Href = 'https://books.rob.me.uk/discover/stored'; External = $true }
        @{ Title = 'Request';        Href = 'https://request-books.rob.me.uk';         External = $true }
        @{ Title = 'Lists';   Href = '/lists';                                  External = $false }
        @{ Title = 'How To';  Href = '/how-to-use';                             External = $false }
    )
    Set-PodeState -Name 'NavItems' -Value $script:NavItems | Out-Null

    # Ensure the per-user prefs dir exists.
    $stateDir = Get-Cfg 'DASH_STATE_DIR' '/userprefs'
    if (-not (Test-Path $stateDir)) {
        New-Item -ItemType Directory -Path $stateDir -Force | Out-Null
    }

    # --- cached file reader: re-reads a file only when its mtime changes, so
    #     pages load fast (no disk hit per request) but edits appear on refresh.
    #     Cache lives in Pode state, keyed by path.
    function Read-CachedFile([string]$path) {
        if (-not (Test-Path $path)) { return $null }
        $mtime = (Get-Item $path).LastWriteTimeUtc.Ticks
        $cacheKey = "filecache::$path"
        $cached = $null
        try { $cached = Get-PodeState -Name $cacheKey } catch { }
        if ($cached -and $cached.Mtime -eq $mtime) { return $cached.Content }
        $content = Get-Content $path -Raw
        Set-PodeState -Name $cacheKey -Value @{ Mtime = $mtime; Content = $content } | Out-Null
        return $content
    }

    # --- greeting: read from users.json (single source of truth, editable) ---
    # Resolution: explicit 'greeting' wins; else 'name' filled into the
    # defaultGreeting template ({name}); else plain default with {name} stripped.
    function Resolve-Greeting([string]$email) {
        $dir  = Get-PodeState -Name 'CfgDir'
        $json = Read-CachedFile (Join-Path $dir 'users.json')
        $defaultTpl = 'Welcome to the library.'

        # helper: substitute {name} (or strip it cleanly if no name)
        $fill = {
            param($text, $name)
            if ($name) { return ($text -replace '\{name\}', [string]$name) }
            return ($text -replace '\s*\{name\}', '' -replace '\{name\}', '')
        }

        if ($json) {
            try {
                $obj = $json | ConvertFrom-Json
                if ($obj.defaultGreeting) { $defaultTpl = [string]$obj.defaultGreeting }
                $match = $obj.users | Where-Object { $_.email -eq $email } | Select-Object -First 1
                if ($match) {
                    $name = if ($match.name) { [string]$match.name } else { '' }

                    # 1) a list of greetings -> pick one at random
                    if ($match.greetings -and @($match.greetings).Count -gt 0) {
                        $list = @($match.greetings)
                        $pick = $list[(Get-Random -Maximum $list.Count)]
                        return (& $fill ([string]$pick) $name)
                    }
                    # 2) a single explicit greeting
                    if ($match.greeting) {
                        return (& $fill ([string]$match.greeting) $name)
                    }
                    # 3) name only -> templated default
                    if ($name) {
                        return (& $fill $defaultTpl $name)
                    }
                }
            } catch { "WARN: users.json parse failed: $_" | Out-Default }
        }
        # unknown user (or no name): default template with {name} tidied away
        return (& $fill $defaultTpl '')
    }

    # --- markdown -> HTML for any editable .md in the config dir (cached by
    #     mtime so we don't re-render per hit). Returns '' if the file is absent.
    function Get-MarkdownHtml([string]$filename) {
        $dir  = Get-PodeState -Name 'CfgDir'
        $path = Join-Path $dir $filename
        if (-not (Test-Path $path)) { return '' }
        $mtime = (Get-Item $path).LastWriteTimeUtc.Ticks
        $cacheKey = "mdcache::$path"
        $cached = $null
        try { $cached = Get-PodeState -Name $cacheKey } catch { }
        if ($cached -and $cached.Mtime -eq $mtime) { return $cached.Html }
        try {
            $html = (ConvertFrom-Markdown -Path $path).Html
            Set-PodeState -Name $cacheKey -Value @{ Mtime = $mtime; Html = $html } | Out-Null
            return $html
        } catch {
            "WARN: $filename render failed: $_" | Out-Default
            return ''
        }
    }

    # --- instructions: render instructions.md -> HTML (editable, no rebuild) ---
    function Get-InstructionsHtml { return (Get-MarkdownHtml 'instructions.md') }

    # --- lists index: render web/lists.md (hand-written index of links). The
    #     index links to subpages (/lists/<name>) and/or external URLs.
    function Get-ListsHtml { return (Get-MarkdownHtml 'lists.md') }

    # --- a single named sublist: render web/lists/<name>.md as its own page.
    #     <name> is sanitised to one path segment (letters, digits, dash,
    #     underscore) so a request can't escape the lists dir (no .., no /).
    #     Returns '' if the name is invalid or the file is absent.
    function Get-SubListHtml([string]$name) {
        if ([string]::IsNullOrWhiteSpace($name)) { return '' }
        if ($name -notmatch '^[A-Za-z0-9_-]+$') {
            "WARN: rejected sublist name '$name' (illegal chars)" | Out-Default
            return ''
        }
        $html = Get-MarkdownHtml (Join-Path 'lists' "$name.md")
        if (-not $html) { return '' }
        # Book numbers are AUTO-GENERATED by a CSS counter (see template), not
        # typed in the markdown. Here we:
        #  1) strip any leading "NNN." a list might still contain (so old numbered
        #     lists don't double up), then
        #  2) inject an EMPTY <span class="booknum"></span> into every book <h4>
        #     as the hook the CSS counter writes the number into.
        # First strip a leading number if present:
        $html = [regex]::Replace($html, '(?<=<h4[^>]*>)\s*\d+\.\s*', '')
        # Then add the counter hook to every h4 (idempotent: only if absent):
        # inject the counter hook with NO trailing space — the span is an
        # inline-block of fixed width that spans rail-1→rail-2, so a trailing
        # space would push the title ~4px past rail 2 (misaligning it with the
        # body, which is at rail 2).
        $html = [regex]::Replace(
            $html,
            '(<h4[^>]*>)(?!\s*<span class="booknum")',
            '$1<span class="booknum"></span>'
        )
        # NOTE: a future "[resetnum]" / "[resetnum N]" marker is intended to
        # restart numbering mid-list, but a correct CSS-counter reset needs a
        # per-section wrapper (a bare counter-reset mid-list nests rather than
        # resets). Not implemented yet — for now we just STRIP any [resetnum]
        # marker so it never shows as literal text in a list.
        $html = [regex]::Replace($html, '(?s)<p>\s*\[resetnum(?:\s+\d+)?\]\s*</p>', '')
        # Inside author <h5> lines, turn " | " into a styled divider span (more
        # space + lighter colour). Scoped to h5 so pipes elsewhere are untouched.
        $html = [regex]::Replace(
            $html,
            '(<h5[^>]*>)(.*?)(</h5>)',
            {
                param($m)
                $inner = $m.Groups[2].Value -replace '\s*\|\s*', '<span class="sep">|</span>'
                $m.Groups[1].Value + $inner + $m.Groups[3].Value
            }
        )
        # Book covers: list markdown references a cover as plain ![](covers/<id>.jpg),
        # optionally wrapped in a link: [![](covers/<id>.jpg)](url). ConvertFrom-Markdown
        # renders an <img src="covers/<id>.jpg" .../>. Two order-independent passes:
        #   1) rewrite ANY cover src to an ABSOLUTE "/covers/<id>.jpg". The page is
        #      served at /lists/<name>, so a RELATIVE "covers/..." resolves to
        #      /lists/covers/... and 404s. Matches both "covers/..." and a stray
        #      "/lists/covers/..." just in case. Done first so pass 2 keys off /covers/.
        #   2) add class="bookcover" to any <img> whose src is /covers/... and that
        #      isn't already classed. Independent of attribute order, and works whether
        #      or not the <img> is wrapped in an <a>. Idempotent on re-render.
        $html = [regex]::Replace($html, '\bsrc="(?:/lists/)?covers/', 'src="/covers/')
        $html = [regex]::Replace(
            $html,
            '<img(?![^>]*\bclass=)([^>]*\bsrc="/covers/[^"]+"[^>]*?)/?>',
            '<img class="bookcover"$1/>'
        )

        # Per-book structure. The title (<h4>) stays on its own at the top. The
        # rest of the book is split into:
        #   .book-head : the cover + the h5 rows (author/tags/footer), laid out as
        #                a flex row with the h5 group vertically CENTRED against
        #                the cover's height.
        #   then the <p> description paragraphs, which follow .book-head and so
        #                always start BELOW the cover, full width at rail 1.
        # Coverless books: .book-head still holds the h5 rows (no cover), and the
        # body follows — looks the same as a normal stacked entry.
        $coverPat = '(?s)(?:<p>\s*)?(?:<a\b[^>]*>\s*)?<img\b[^>]*\bclass="bookcover"[^>]*/?>(?:\s*</a>)?(?:\s*</p>)?'
        $h4idx = $html.IndexOf('<h4')
        if ($h4idx -ge 0) {
            $intro = $html.Substring(0, $h4idx)
            $rest  = $html.Substring($h4idx)
            $chunks = [regex]::Split($rest, '(?=<h4)') | Where-Object { $_ -ne '' }
            $books = foreach ($chunk in $chunks) {
                $mh = [regex]::Match($chunk, '(?s)^\s*<h4\b.*?</h4>')
                if (-not $mh.Success) { $chunk; continue }
                $title = $mh.Value
                $after = $chunk.Substring($mh.Index + $mh.Length)

                # Pull the cover out of $after (if present).
                $cover = ''
                $mc = [regex]::Match($after, $coverPat)
                if ($mc.Success) {
                    # keep just the <a><img></a> (or bare <img>) — drop any <p> wrapper
                    $inner = [regex]::Match($mc.Value, '(?s)(?:<a\b[^>]*>\s*)?<img\b[^>]*\bclass="bookcover"[^>]*/?>(?:\s*</a>)?')
                    $cover = $inner.Value
                    $after = $after.Remove($mc.Index, $mc.Length)
                }

                # Split remaining markup into h5 rows (meta) vs everything else (body).
                # h5 rows go in .book-meta (centred beside the cover); the rest is
                # the body, placed after .book-head so it sits below the cover.
                $metaSb = [System.Text.StringBuilder]::new()
                foreach ($m in [regex]::Matches($after, '(?s)<h5\b.*?</h5>')) {
                    [void]$metaSb.Append($m.Value)
                }
                $body = [regex]::Replace($after, '(?s)<h5\b.*?</h5>', '')
                # A section heading (<h2>/<h3>) can appear AFTER a book (e.g. a
                # "## Honourable mentions" divider mid-list). Such a heading is part
                # of $after, so it would otherwise get wrapped inside this book's
                # .book-flow — which breaks position:sticky (it'd stick relative to
                # the small wrapper, not the page). Split it out: everything from the
                # first h2/h3 onward is emitted AFTER the book wrapper, as a
                # top-level sibling of .booklist-page (where sticky works).
                $trailing = ''
                $ms = [regex]::Match($body, '(?s)<h[23]\b')
                if ($ms.Success) {
                    $trailing = $body.Substring($ms.Index)
                    $body     = $body.Substring(0, $ms.Index)
                }
                # Tag the FIRST body paragraph as the lead (prominent blue intro).
                # The old `h5 + p` selector no longer matches now that h5s live in
                # .book-meta and the body is a separate sibling, so we mark it here.
                # BUT if the book opens with a blockquote (markdown '> …', used as
                # an attributed pull-quote), that quote IS the lead — leave it as a
                # <blockquote> and don't promote a later <p>. Only tag the first
                # <p> when no <blockquote> precedes it. Regex instance caps at 1.
                if ($body.TrimStart() -notmatch '^<blockquote') {
                    $body = ([regex]'<p>').Replace($body, '<p class="lead">', 1)
                }
                $coverHtml = if ($cover) { "<div class=`"book-cover`">$cover</div>" } else { '' }
                $metaHtml  = "<div class=`"book-meta`">$($metaSb.ToString())</div>"
                $headHtml  = "<div class=`"book-head`">$coverHtml$metaHtml</div>"
                $flowClass = 'book-flow'
                # v30: RESTORED the <div class="book"> wrapper (v29 had removed it).
                # The wrapper bounds each sticky h4 to its own book, which is what
                # makes a finished title ride up and clear instead of overlapping
                # the next one. Without it, every h4 shares the same sticky `top`,
                # so a new (one-line) h4 just paints over a previous (two-line) one
                # at that slot and the previous title's SECOND line shows below the
                # new title. v29 was removed on the theory the wrapper stopped short
                # books pinning, but the real cause then was the old fixed-offset
                # ladder; with the template's JS slot-tracker (v77) setting the h4
                # offset from the live section-bar height, short books pin fine AND
                # tall titles clear. h4 stays the FIRST child of .book so sticky
                # resolves against the wrapper.
                # $trailing (a section h2/h3 after a book) stays OUTSIDE the wrapper
                # as a direct child of .booklist-page, which its own sticky needs.
                "<div class=`"book`">$title<div class=`"$flowClass`">$headHtml$body</div></div>$trailing"
            }
            $html = $intro + ($books -join "`n")
        }
        return $html
    }

    # ------------------------------------------------------------------------
    #  IDENTITY: verify the Cloudflare Access JWT, return the email or $null.
    # ------------------------------------------------------------------------
    function Get-VerifiedUser {
        if ((Get-Cfg 'DASH_DEVMODE' 'false') -eq 'true') {
            return (Get-Cfg 'DASH_DEVEMAIL' 'rob@rob.me.uk')
        }

        $teamDomain = Get-Cfg 'CF_TEAM_DOMAIN' ''
        $accessAud  = Get-Cfg 'CF_ACCESS_AUD' ''
        if ([string]::IsNullOrWhiteSpace($teamDomain)) {
            "AUTH FAIL: CF_TEAM_DOMAIN not set" | Out-Default
            return $null
        }

        $jwt = Get-PodeHeader -Name 'Cf-Access-Jwt-Assertion'
        if ([string]::IsNullOrWhiteSpace($jwt)) {
            "AUTH FAIL: no Cf-Access-Jwt-Assertion header" | Out-Default
            return $null
        }

        $parts = $jwt.Split('.')
        if ($parts.Count -ne 3) { "AUTH FAIL: JWT not 3 parts (got $($parts.Count))" | Out-Default; return $null }

        function ConvertFrom-B64Url([string]$s) {
            $s = $s.Replace('-', '+').Replace('_', '/')
            switch ($s.Length % 4) { 2 { $s += '==' } 3 { $s += '=' } }
            return [Convert]::FromBase64String($s)
        }

        $header  = [Text.Encoding]::UTF8.GetString((ConvertFrom-B64Url $parts[0])) | ConvertFrom-Json
        $payload = [Text.Encoding]::UTF8.GetString((ConvertFrom-B64Url $parts[1])) | ConvertFrom-Json

        # fetch + cache Cloudflare's signing keys (JWKS)
        $certsUrl = "$teamDomain/cdn-cgi/access/certs"
        $jwks = $null; $jwksAge = $null
        try { $jwks = Get-PodeState -Name 'jwks'; $jwksAge = Get-PodeState -Name 'jwksAt' } catch { }
        if (-not $jwks -or -not $jwksAge -or ((Get-Date) - $jwksAge).TotalMinutes -gt 60) {
            try {
                $jwks = Invoke-RestMethod -Uri $certsUrl -TimeoutSec 10
                Set-PodeState -Name 'jwks'   -Value $jwks      | Out-Null
                Set-PodeState -Name 'jwksAt' -Value (Get-Date) | Out-Null
            } catch {
                "AUTH FAIL: JWKS fetch failed from ${certsUrl}: $_" | Out-Default
                return $null
            }
        }

        $key = $jwks.keys | Where-Object { $_.kid -eq $header.kid } | Select-Object -First 1
        if (-not $key) { "AUTH FAIL: no JWKS key matching kid=$($header.kid)" | Out-Default; return $null }

        try {
            $rsa = [Security.Cryptography.RSA]::Create()
            $rsa.ImportParameters([Security.Cryptography.RSAParameters]@{
                Modulus  = ConvertFrom-B64Url $key.n
                Exponent = ConvertFrom-B64Url $key.e
            })
            $signed = [Text.Encoding]::ASCII.GetBytes("$($parts[0]).$($parts[1])")
            $sig    = ConvertFrom-B64Url $parts[2]
            $ok = $rsa.VerifyData($signed, $sig,
                [Security.Cryptography.HashAlgorithmName]::SHA256,
                [Security.Cryptography.RSASignaturePadding]::Pkcs1)
            if (-not $ok) { "AUTH FAIL: signature did not verify" | Out-Default; return $null }
        } catch {
            "AUTH FAIL: signature verify threw: $_" | Out-Default
            return $null
        }

        $now = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
        if ($payload.exp -and $payload.exp -lt $now) { "AUTH FAIL: token expired" | Out-Default; return $null }
        if ($payload.iss -and $payload.iss -ne $teamDomain) {
            "AUTH FAIL: issuer mismatch. token iss=$($payload.iss) expected=$teamDomain" | Out-Default; return $null
        }
        if ($accessAud) {
            $auds = @($payload.aud)
            if ($auds -notcontains $accessAud) {
                "AUTH FAIL: aud mismatch. token aud=$($auds -join ',') expected=$accessAud" | Out-Default; return $null
            }
        }

        if ($payload.email) { return [string]$payload.email }
        "AUTH FAIL: no email claim. claims=$($payload.PSObject.Properties.Name -join ',')" | Out-Default
        return $null
    }

    # ------------------------------------------------------------------------
    #  STORAGE
    # ------------------------------------------------------------------------
    function Get-PrefPath([string]$email) {
        $dir = Get-Cfg 'DASH_STATE_DIR' '/userprefs'
        $safe = $email -replace '[^a-zA-Z0-9@._-]', '_'
        return (Join-Path $dir "$safe.json")
    }

    function Get-UserPrefs([string]$email) {
        $defs = Get-PodeState -Name 'ToggleDefs'
        $path = Get-PrefPath $email
        $prefs = @{}
        foreach ($t in $defs) { $prefs[$t.Key] = $t.Default }
        if (Test-Path $path) {
            try {
                $existing = Get-Content $path -Raw | ConvertFrom-Json
                foreach ($t in $defs) {
                    if ($t.Expiry) {
                        # Expiry toggle: stored as "<Key>Until" = epoch-seconds expiry.
                        # 'on' iff that timestamp is in the future.
                        $untilKey = "$($t.Key)Until"
                        $until = $existing.$untilKey
                        if ($null -ne $until) {
                            $now = [int][double]::Parse((Get-Date -UFormat %s))
                            $prefs[$t.Key] = ([int64]$until -gt $now)
                        }
                    } elseif ($null -ne $existing.$($t.Key)) {
                        $prefs[$t.Key] = [bool]$existing.$($t.Key)
                    }
                }
            } catch { "Bad prefs file ${path}: $_" | Out-Default }
        }
        return $prefs
    }

    function Set-UserToggle([string]$email, [string]$key, [bool]$value) {
        $defs = Get-PodeState -Name 'ToggleDefs'
        $def  = $defs | Where-Object { $_.Key -eq $key } | Select-Object -First 1
        if (-not $def) { throw "Unknown toggle '$key'" }
        # Per-user restriction: if the toggle defines Users, only they may set it.
        if ($def.Users -and ($def.Users -notcontains $email)) {
            throw "Toggle '$key' is not available for $email"
        }
        $path = Get-PrefPath $email
        $lock = "$path.lock"
        $tries = 0
        while ((Test-Path $lock) -and $tries -lt 50) { Start-Sleep -Milliseconds 20; $tries++ }
        New-Item -ItemType File -Path $lock -Force | Out-Null
        try {
            # Read the raw existing JSON so we preserve all keys (incl. *Until).
            $raw = @{}
            if (Test-Path $path) {
                try {
                    $obj = Get-Content $path -Raw | ConvertFrom-Json
                    foreach ($p in $obj.PSObject.Properties) { $raw[$p.Name] = $p.Value }
                } catch { }
            }
            if ($def.Expiry) {
                # Expiry toggle: store an absolute expiry timestamp (epoch seconds).
                $untilKey = "$($key)Until"
                if ($value) {
                    $now = [int][double]::Parse((Get-Date -UFormat %s))
                    $raw[$untilKey] = $now + [int]$def.Expiry
                } else {
                    $raw[$untilKey] = 0   # cleared / in the past = off
                }
            } else {
                $raw[$key] = $value
            }
            ($raw | ConvertTo-Json) | Set-Content $path
        } finally {
            Remove-Item $lock -Force -ErrorAction SilentlyContinue
        }
    }

    # ------------------------------------------------------------------------
    #  SHARED RENDER HELPERS (used by /, /lists, /how-to-use so they all get the
    #  same template + nav bar)
    # ------------------------------------------------------------------------

    # Build the top nav bar HTML. Marks the current page so CSS can highlight it.
    # External items get target=_blank+rel=noopener (harmless for same-tab apps,
    # and means Browse/Request open in a new tab, leaving the dashboard intact).
    function Get-NavHtml([string]$current) {
        $items = Get-PodeState -Name 'NavItems'
        $parts = $items | ForEach-Object {
            if ($_.External) {
                "<a href=`"$($_.Href)`" class=`"nav-link`" target=`"_blank`" rel=`"noopener`">$($_.Title)</a>"
            } else {
                "<a href=`"$($_.Href)`" class=`"nav-link`">$($_.Title)</a>"
            }
        }
        return "<nav class=`"topnav`">$($parts -join '')</nav>"
    }

    # Read template (mtime-cached) with a minimal fallback. Returns the raw
    # template HTML with tokens still present.
    function Get-TemplateHtml {
        $cfgDir  = Get-PodeState -Name 'CfgDir'
        $tplPath = Join-Path $cfgDir 'template.html'
        $html    = Read-CachedFile $tplPath
        if (-not $html) {
            "TEMPLATE ERROR: $tplPath not found — serving minimal fallback page" | Out-Default
            $html = @"
<!DOCTYPE html><html><head><meta charset="utf-8"><title>...Gunit!</title></head>
<body style="font-family:sans-serif;background:#1c1f24;color:#ccc;padding:40px">
{{NAV}}<h1 class="brand-title">...Gunit!</h1><p>{{GREETING}}</p><p>Signed in as {{EMAIL}}</p>
{{LINKS}}<h2>My Settings</h2>{{TOGGLES}}<p id="status"></p>
<div>{{CONTENT}}</div>
<p style="opacity:.5">(template file not found at $tplPath)</p>
<script>
let statusTimeout;
async function saveToggle(el){const s=document.getElementById('status');clearTimeout(statusTimeout);s.innerText='Saving...';
try{const r=await fetch('/toggle',{method:'POST',headers:{'Content-Type':'application/json'},
body:JSON.stringify({key:el.dataset.key,value:el.checked})});s.innerText=r.ok?'Saved.':'Error saving.';
if(!r.ok)el.checked=!el.checked;}catch(e){s.innerText='Network error.';el.checked=!el.checked;}
statusTimeout=setTimeout(()=>{s.innerText='';},2500);}
</script></body></html>
"@
        }
        return $html
    }

    # Substitute all tokens. Any token not supplied for a given page is replaced
    # with '' so secondary pages (lists, how-to-use) don't show stray {{...}}.
    function Resolve-Tokens([string]$html, [hashtable]$tok) {
        foreach ($name in @('NAV','HOME','CONTENT','GREETING','EMAIL','LINKS','TOGGLES','INSTRUCTIONS')) {
            $val = if ($tok.ContainsKey($name)) { [string]$tok[$name] } else { '' }
            $html = $html.Replace("{{$name}}", $val)
        }
        return $html
    }

    # ------------------------------------------------------------------------
    #  IMAGE ROUTES for editable image dirs under the config dir.
    #  Served via explicit Add-PodeRoute (NOT Add-PodeStaticRoute): on Pode
    #  2.13.2 the static routes registered but silently 404'd on every file.
    #  This uses the same dynamic-route + Get-PodeState pattern as /lists/:name
    #  (which works), with a strict single-segment filename gate to block path
    #  traversal, then streams the file with Write-PodeFileResponse.
    #    /screenshots/<file>  <- <cfgDir>/screenshots       (How-To markdown images)
    #    /covers/<file>       <- <cfgDir>/lists/covers       (book-list cover images)
    #
    #  NOTE (v18): covers live in <cfgDir>/lists/covers (next to the list .md
    #  files that reference them, where link-md writes them), NOT <cfgDir>/covers.
    # ------------------------------------------------------------------------
    "STATIC: /screenshots/:file -> $(Join-Path $cfgDir 'screenshots')" | Out-Default
    Add-PodeRoute -Method Get -Path '/screenshots/:file' -ScriptBlock {
        $file = $WebEvent.Parameters['file']
        if ([string]::IsNullOrWhiteSpace($file) -or $file -notmatch '^[A-Za-z0-9._-]+$') {
            Write-PodeTextResponse -Value 'bad filename' -StatusCode 400; return
        }
        $path = Join-Path (Join-Path (Get-PodeState -Name 'CfgDir') 'screenshots') $file
        if (Test-Path $path -PathType Leaf) {
            Write-PodeFileResponse -Path $path
        } else {
            Write-PodeTextResponse -Value 'not found' -StatusCode 404
        }
    }

    "STATIC: /covers/:file -> $(Join-Path $cfgDir 'lists/covers')" | Out-Default
    Add-PodeRoute -Method Get -Path '/covers/:file' -ScriptBlock {
        $file = $WebEvent.Parameters['file']
        if ([string]::IsNullOrWhiteSpace($file) -or $file -notmatch '^[A-Za-z0-9._-]+$') {
            Write-PodeTextResponse -Value 'bad filename' -StatusCode 400; return
        }
        $path = Join-Path (Join-Path (Get-PodeState -Name 'CfgDir') 'lists/covers') $file
        if (Test-Path $path -PathType Leaf) {
            Write-PodeFileResponse -Path $path
        } else {
            Write-PodeTextResponse -Value 'not found' -StatusCode 404
        }
    }

    # Favicon: served the same proven dynamic-route way (static routes 404 on
    # this Pode build). The <head> link in template.html points at /favicon.ico.
    # Drop favicon.ico into <cfgDir>; if it's absent the route still answers but
    # returns 404 (harmless — the browser just shows its default icon). To swap
    # the icon, replace the file — no rebuild needed; only this wiring is baked.
    "STATIC: /favicon.ico -> $(Join-Path $cfgDir 'favicon.ico')" | Out-Default
    Add-PodeRoute -Method Get -Path '/favicon.ico' -ScriptBlock {
        $path = Join-Path (Get-PodeState -Name 'CfgDir') 'favicon.ico'
        if (Test-Path $path -PathType Leaf) {
            Write-PodeFileResponse -Path $path
        } else {
            Write-PodeTextResponse -Value 'not found' -StatusCode 404
        }
    }

    # ------------------------------------------------------------------------
    #  ROUTE: dashboard home
    # ------------------------------------------------------------------------
    Add-PodeRoute -Method Get -Path '/' -ScriptBlock {
      try {
        $email = Get-VerifiedUser
        if (-not $email) {
            Write-PodeTextResponse -Value 'Not authenticated.' -StatusCode 401
            return
        }
        $prefs    = Get-UserPrefs $email
        $greeting = Resolve-Greeting $email
        $links    = Get-PodeState -Name 'DashLinks'
        $defs     = Get-PodeState -Name 'ToggleDefs'

        $linksHtml = ($links | ForEach-Object {
            $label = $_.Title
            if ($_.Sub) { $label += "<span class=`"custom-link-sub`">$($_.Sub)</span>" }
            if ($_.External) {
                "<a href=`"$($_.Url)`" class=`"custom-link`" target=`"_blank`" rel=`"noopener`">$label</a>"
            } else {
                "<a href=`"$($_.Url)`" class=`"custom-link`">$label</a>"
            }
        }) -join "`n"

        $togglesHtml = ($defs | Where-Object {
            -not $_.Users -or ($_.Users -contains $email)
        } | ForEach-Object {
            $checked = if ($prefs[$_.Key]) { 'checked' } else { '' }
            @"
<label class="toggle">
  <input type="checkbox" data-key="$($_.Key)" $checked onchange="saveToggle(this)" />
  <span>$($_.Label)</span>
</label>
"@
        }) -join "`n"

        $html = Get-TemplateHtml
        $homeHtml = @"
<div class="custom-section">
  <h1 class="brand-title">...Gunit!</h1>
  <p class="greeting">$greeting</p>
  <p class="whoami">Signed in as <strong>$email</strong></p>
  $linksHtml
</div>
<div class="custom-section" style="border-top: 2px solid rgba(255,255,255,0.05); padding-top: 30px;">
  $togglesHtml
  <p id="status"></p>
</div>
"@
        $html = Resolve-Tokens $html @{
            NAV  = (Get-NavHtml '/')
            HOME = $homeHtml
        }
        Write-PodeHtmlResponse -Value $html
      } catch {
        Write-PodeTextResponse -StatusCode 500 -Value "ERROR in GET /: $($_.Exception.Message)`n`n$($_.ScriptStackTrace)"
      }
    }

    # ------------------------------------------------------------------------
    #  ROUTE: Lists page (renders lists.md — editable, no rebuild)
    # ------------------------------------------------------------------------
    Add-PodeRoute -Method Get -Path '/lists' -ScriptBlock {
      try {
        $email = Get-VerifiedUser
        if (-not $email) { Write-PodeTextResponse -Value 'Not authenticated.' -StatusCode 401; return }
        $body = Get-ListsHtml
        if (-not $body) { $body = '<p>No lists yet. Create <code>lists.md</code> in the web config dir.</p>' }
        $html = Get-TemplateHtml
        $html = Resolve-Tokens $html @{
            NAV     = (Get-NavHtml '/lists')
            CONTENT = "<div class=`"custom-section`"><h1>Lists of Books</h1><div class=`"instructions`">$body</div></div>"
        }
        Write-PodeHtmlResponse -Value $html
      } catch {
        Write-PodeTextResponse -StatusCode 500 -Value "ERROR in GET /lists: $($_.Exception.Message)`n`n$($_.ScriptStackTrace)"
      }
    }

    # ------------------------------------------------------------------------
    #  ROUTE: an individual list subpage — renders web/lists/<name>.md
    #  Linked from the index (lists.md) as [Title](/lists/<name>). Editable,
    #  no rebuild: drop a new web/lists/<name>.md and link to it.
    # ------------------------------------------------------------------------
    Add-PodeRoute -Method Get -Path '/lists/:name' -ScriptBlock {
      try {
        $email = Get-VerifiedUser
        if (-not $email) { Write-PodeTextResponse -Value 'Not authenticated.' -StatusCode 401; return }
        $name = $WebEvent.Parameters['name']
        $body = Get-SubListHtml $name
        if (-not $body) {
            Write-PodeHtmlResponse -StatusCode 404 -Value (Resolve-Tokens (Get-TemplateHtml) @{
                NAV     = (Get-NavHtml '/lists')
                CONTENT = "<div class=`"custom-section`"><h1>List not found</h1><div class=`"instructions`"><p>No list called <code>$([System.Net.WebUtility]::HtmlEncode($name))</code>. <a href=`"/lists`">Back to all lists</a>.</p></div></div>"
            })
            return
        }
        $html = Resolve-Tokens (Get-TemplateHtml) @{
            NAV     = (Get-NavHtml '/lists')
            CONTENT = "<div class=`"custom-section`"><div class=`"booklist-page`">$body</div><p style=`"margin-top:24px`"><a href=`"/lists`" class=`"booklist-back`">&larr; All lists</a></p></div>"
        }
        Write-PodeHtmlResponse -Value $html
      } catch {
        Write-PodeTextResponse -StatusCode 500 -Value "ERROR in GET /lists/:name: $($_.Exception.Message)`n`n$($_.ScriptStackTrace)"
      }
    }

    # ------------------------------------------------------------------------
    #  ROUTE: How To Use page (renders instructions.md — now its own page)
    # ------------------------------------------------------------------------
    Add-PodeRoute -Method Get -Path '/how-to-use' -ScriptBlock {
      try {
        $email = Get-VerifiedUser
        if (-not $email) { Write-PodeTextResponse -Value 'Not authenticated.' -StatusCode 401; return }
        $body = Get-InstructionsHtml
        if (-not $body) { $body = '<p>No instructions yet. Create <code>instructions.md</code> in the config dir.</p>' }
        $html = Get-TemplateHtml
        $html = Resolve-Tokens $html @{
            NAV     = (Get-NavHtml '/how-to-use')
            CONTENT = "<div class=`"custom-section`"><h1>How To Use</h1><div class=`"instructions howto-page`">$body</div></div>"
        }
        Write-PodeHtmlResponse -Value $html
      } catch {
        Write-PodeTextResponse -StatusCode 500 -Value "ERROR in GET /how-to-use: $($_.Exception.Message)`n`n$($_.ScriptStackTrace)"
      }
    }

    # ------------------------------------------------------------------------
    #  ROUTE: flip one toggle for the current user
    # ------------------------------------------------------------------------
    Add-PodeRoute -Method Post -Path '/toggle' -ScriptBlock {
        $email = Get-VerifiedUser
        if (-not $email) { Write-PodeTextResponse -Value 'Not authenticated' -StatusCode 401; return }
        $key   = $WebEvent.Data.key
        $value = [bool]$WebEvent.Data.value
        try {
            Set-UserToggle -email $email -key $key -value $value
            Write-PodeJsonResponse -Value @{ ok = $true; key = $key; value = $value }
        } catch {
            Write-PodeTextResponse -Value "$_" -StatusCode 400
        }
    }

    # ------------------------------------------------------------------------
    #  ROUTE: JSON API for the pipeline to query prefs (optional)
    # ------------------------------------------------------------------------
    Add-PodeRoute -Method Get -Path '/api/prefs' -ScriptBlock {
        $email = Get-VerifiedUser
        if (-not $email) { Write-PodeTextResponse -Value 'Not authenticated' -StatusCode 401; return }
        Write-PodeJsonResponse -Value (Get-UserPrefs $email)
    }
}

# =============================================================================
#  UserDashboard.ps1
#  Version v31
# =============================================================================